config/routes.rb
Rails.application.routes.draw do
  

  resources :goals
  resources :campaigns
  resources :users

  root 'welcome#index'

  get '/login' => 'session#new'

  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'
  get 'welcome/index'
  get 'campaigns/points/new' => 'points#new'
  post 'campaigns/points/new' => 'points#create'
  post 'campaigns/join' => 'campaigns#join'
  post 'campaigns/completed' => 'campaigns#complete'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
	has_many :campaigns_users
	has_many :users, through: :campaigns_users
  has_many :mods
  has_many :points
  has_many :users, through: :mods
  has_many :goals

  def self.search(search)
    if search
      where("title like ?", "%#{@search}%")
    else
      find(:all)
    end
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.search(params[:search])
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @campaign = Campaign.find_by(id: params[:id])
    @daily = @campaign.goals.where(time: 1)
    @daily.each do |inst|
      if (!(inst.calculate))
        @daily.remove(inst)
      end
    end
    @weekly = @campaign.goals.where(time: 7)
    @weekly.each do |inst|
      if (!(inst.calculate))
        @weekly.remove(inst)
      end
    end
    @monthly = @campaign.goals.where(time: 31)
    @monthly.each do |inst|
      if (!(inst.calculate))
        @monthly.remove(inst)
      end
    end
    @yearly = @campaign.goals.where(time: 360)
    @yearly.each do |inst|
      if (!(inst.calculate))
        @yearly.remove(inst)
      end
    end
    @points = 0
    if (logged_in?)
      current_user.goals.where(campaign_id: @campaign.id).each do |item|
        @points += item.points
      end
    end
  end

  def join
    @campaign = Campaign.find_by(id: params[:campaign])
    @campaign.users << current_user
    current_user.campaigns << @campaign
    current_user.save
    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully joined.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def complete
    @campaign = Campaign.find_by(id: params[:campaign])
    @goal = Goal.find_by(id: params[:goal])
    current_user.goals << @goal
    respond_to do |format|
      if current_user.save
        format.html { redirect_to @campaign, notice: 'Complete' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end



  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)
    @mod = Mod.create(:email => current_user.email)
    @campaign.mods << @mod
    current_user.mods << @mod

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:title, :description)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= form_for(@campaign) do |f| %>
  <% if @campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% @campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form' %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<p id="notice"><%= notice %></p>
<div align="center">
<h1>Listing Campaigns</h1>

<table border="1" style="width:600px; background-color:#FFF;">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= link_to campaign.title, campaign %></td>
        <td><%= campaign.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign', new_campaign_path %>
</div>

app/views/campaigns/new.html.erb
<body class="message">
	<div class="container">
		<div class="vertical-center-row">
			<div align="center">
				<h1>New Campaign</h1>
				<%= render 'form' %>
			</div>
		</div>
	</div>
</body>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>
<div align="center">
<p>
  <h1>
    <%= @campaign.title %>
  </h1>
</p>
<p>
  <%= @campaign.description %>
</p>
</div>
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-4">
    <strong> Today's Goals: </strong>
    <table border="1" style="width:400px; background-color:#FFF;">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Points</th>
          <th>Complete</th>
        </tr>
      </thead>
      <tbody>
        <% if @daily != nil %> 
          <% @daily.each do |item| %>
          <tr>
            <td>
              <%= item.title %> 
            </td>
            <td>
              <%= link_to item.content, "http://#{item.content}"%>
            </td>
            <td>
              <%= item.points %> 
            </td>
            <td>
              <% if logged_in? %>
                <% if (current_user.hascampaign(@campaign.id)) %>
                  <% unless (current_user.hasgoal(item.id)) %>
                    <%= form_tag 'completed' do |f| %>
                      <p>
                        <%= hidden_field_tag :goal, item.id %>
                        <%= hidden_field_tag :campaign, @campaign.id %>
                        <%= submit_tag "Mark Complete" %>
                      </p>
                    <% end %>
                  <% else %>
                    Complete!
                  <% end %>
                <% end %>
              <% end %>
            </td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    Other Goals:
    <table border="1" style="width:400px; background-color:#FFF;">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Points</th>
          <th>Complete</th>
        </tr>
      </thead>
      <tbody>
        <% if @weekly != nil %> 
          <% @weekly.each do |item| %>
          <tr>
            <td>
              <%= item.title %> 
            </td>
            <td>
              <%= link_to item.content, "http://#{item.content}"%>
            </td>
            <td>
              <%= item.points %> 
            </td>
            <td>
              <% if logged_in? %>
                <% if (current_user.hascampaign(@campaign.id)) %>
                  <% unless (current_user.hasgoal(item.id)) %>
                    <%= form_tag 'completed' do |f| %>
                      <p>
                        <%= hidden_field_tag :goal, item.id %>
                        <%= hidden_field_tag :campaign, @campaign.id %>
                        <%= submit_tag "Mark Complete" %>
                      </p>
                    <% end %>
                  <% else %>
                    Complete!
                  <% end %>
                <% end %>
              <% end %>
            </td>
          </tr>
          <% end %>
        <% end %>
        <% if @monthly != nil %> 
          <% @monthly.each do |item| %>
          <tr>
            <td>
              <%= item.title %> 
            </td>
            <td>
              <%= link_to item.content, "http://#{item.content}"%>
            </td>
            <td>
              <%= item.points %> 
            </td>
            <td>
              <% if logged_in? %>
                <% if (current_user.hascampaign(@campaign.id)) %>
                  <% unless (current_user.hasgoal(item.id)) %>
                    <%= form_tag 'completed' do |f| %>
                      <p>
                        <%= hidden_field_tag :goal, item.id %>
                        <%= hidden_field_tag :campaign, @campaign.id %>
                        <%= submit_tag "Mark Complete" %>
                      </p>
                    <% end %>
                  <% else %>
                    Complete!
                  <% end %>
                <% end %>
              <% end %>
            </td>
          </tr>
          <% end %>
        <% end %>
        <% if @yearly != nil %> 
          <% @yearly.each do |item| %>
          <tr>
            <td>
              <%= item.title %> 
            </td>
            <td>
              <%= link_to item.content, "http://#{item.content}"%>
            </td>
            <td>
              <%= item.points %> 
            </td>
            <td>
              <% if logged_in? %>
                <% if (current_user.hascampaign(@campaign.id)) %>
                  <% unless (current_user.hasgoal(item.id)) %>
                    <%= form_tag 'completed' do |f| %>
                      <p>
                        <%= hidden_field_tag :goal, item.id %>
                        <%= hidden_field_tag :campaign, @campaign.id %>
                        <%= submit_tag "Mark Complete" %>
                      </p>
                    <% end %>
                  <% else %>
                    Complete!
                  <% end %>
                <% end %>
              <% end %>
            </td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-2">
  </div>
  <div class="col-md-4">
    <strong> My Stats: </strong>
    <% if (current_user == nil) %>
      <%= button_to('Login', '/login', :class => 'btn btn-large btn-primary')  %>
    <% elsif (!(current_user.hascampaign(@campaign.id))) %>
      <%= form_tag 'join' do |f| %>
        <p>
          <%= hidden_field_tag :campaign, @campaign.id %>
          <%= hidden_field_tag :user, current_user.id %>
          <%= submit_tag "Join Campaign" %>
        </p>
      <% end %>
    <% else %>
      <br>
      Points:
      <%= @points %>
      <br>
      Level:
      <%= @points/10 %>

    <% end %>

    <!-- <p> 
      <strong> Future Goals: </strong>
      <ol style="text-align:left; list-style-position:inside;">
        <% if @weekly != nil %> 
          <% @weekly.each do |item| %>
          <li>
            <b>
              <%= item.title %>
            </b>
            <br> &emsp; &emsp;
            <%= item.content%>
          </li>
          <br>
          <% end %>
        <% end %>
        <% if @month != nil %> 
          <% @month.each do |item| %>
          <li>
            <b>
              <%= item.title %>
            </b>
            <br> &emsp; &emsp;
            <%= item.content%>
          </li>
          <br>
          <% end %>
        <% end %>
        <% if @year != nil %> 
          <% @year.each do |item| %>
          <li>
            <b>
              <%= item.title %>
            </b>
            <br> &emsp; &emsp;
            <%= item.content%>
          </li>
          <br>
          <% end %>
        <% end %>
      </ol>
    </p> -->
  </div>
  <div class="col-md-2">
  </div>
</div class="row">
<div align="center">
<p>
<% if logged_in? %>
  <% if @campaign.mods.find_by(email: current_user.email) != nil %>
    <%= button_to('New Goal', '/goals/new', :class => 'btn btn-large btn-primary', 
:method => 'get', params: {'campaign_id' => @campaign.id})  %>
  <% end %>
<% end %>
<strong> Mods: </strong> 
<% @campaign.mods.each do |item|%>
	<p>
		<%= item.email %>
	</p>
<% end %>
</p>
</div>