config/routes.rb
Rails.application.routes.draw do
  

  resources :goals
  resources :campaigns
  resources :users

  root 'welcome#index'

  get '/login' => 'session#new'

  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'
  get 'welcome/index'
  get 'campaigns/points/new' => 'points#new'
  post 'campaigns/points/new' => 'points#create'
  post 'campaigns/join' => 'campaigns#join'
  post 'campaigns/completed' => 'campaigns#complete'

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :campaign
  belongs_to :user

  def calculate()
    puts created_at
    puts Time.now
  	end_time = created_at + 86400*time
  	if end_time < Time.now
  		return false
  	else
  		return true
  	end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
    @campaign = Campaign.find_by(id: params[:campaign_id])
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)
    @campaign = Campaign.find(@goal.campaign_id)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @campaign, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:campaign_id, :title, :content, :points, :typed, :time)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label "Type (link, petition, etc)" %><br>
    <%= f.text_field :typed %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.select :time, [["Daily", 1], ["Week", 7], ["Month", 31], ["Year", 360]] %>
  </div>

  <%= f.hidden_field :campaign_id, :value => @campaign.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Goals</h1>

<table>
  <thead>
    <tr>
      <th>Campaign</th>
      <th>Title</th>
      <th>Content</th>
      <th>Points</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.campaign %></td>
        <td><%= goal.title %></td>
        <td><%= goal.content %></td>
        <td><%= goal.points %></td>
        <td><%= goal.type %></td>
        <td><%= link_to 'Show', goal %></td>
        <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
        <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<div align="center">
<h1>New Goal</h1>

<%= render 'form' %>

<%= link_to 'Back', @campaign %>
</div>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Campaign:</strong>
  <%= @goal.campaign %>
</p>

<p>
  <strong>Title:</strong>
  <%= @goal.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @goal.content %>
</p>

<p>
  <strong>Points:</strong>
  <%= @goal.points %>
</p>

<p>
  <strong>Type:</strong>
  <%= @goal.typed %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>